site_name: TrustStore Analyzer
site_description: Audit and visualize certificate truststores.

theme:
  name: material

nav:
  - Home: README.md
  - Contributing: CONTRIBUTING.md

extra:
  use_directory_urls: false
