[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "check_truststore"
version = "1.2.1"
description = "Lightweight certificate trust chain analyzer"
readme = "README.md"
requires-python = ">=3.6"
license = {text = "LGPL-3.0-or-later"}
authors = [{name = "Serge van Thillo", email = "nulleke76@gmail.com"}]
keywords = ["ssl", "x509", "pki", "certificate", "truststore", "audit", "jinja2"]

dependencies = [
    "cryptography < 3.5; python_version <= '3.6'",
    "cryptography >= 3.5; python_version > '3.6'",
    "requests",
    "PyYAML",
]

[project.optional-dependencies]
jinja2 = [
    "Jinja2>=3.0.0; python_version >= '3.7'",
    "Jinja2<3.1.0; python_version <= '3.6'"
]
pydantic = [
    "pydantic>=2.0.0; python_version >= '3.8'"
]
all = [
    "pydantic>=2.0.0; python_version >= '3.8'",
    "Jinja2>=3.0.0; python_version >= '3.7'",
    "Jinja2<3.1.0; python_version <= '3.6'"
]

[project.scripts]
check_truststore = "check_truststore.cli:main"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
check_truststore = ["locale/**/*.mo", "locale/**/*.po"]

[project.urls]
"Homepage" = "https://gitlab.com/nulleke/check_truststore/"
"Source" = "https://gitlab.com/nulleke/check_truststore/"
"Issue Tracker" = "https://gitlab.com/nulleke/check_truststore/-/issues"
"Documentation" = "https://gitlab.com/nulleke/check_truststore/-/blob/main/README.md"
