[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "check_truststore"
version = "1.1.4"
description = "Lightweight certificate trust chain analyzer"
readme = "README.md"
requires-python = ">=3.6"
license = {text = "LGPL-3.0-or-later"}
authors = [{name = "Serge van Thillo", email = "nulleke76@gmail.com"}]
keywords = ["ssl", "x509", "pki", "certificate", "truststore", "audit"]

dependencies = [
    "cryptography",
    "requests",
    "PyYAML",
]

[project.optional-dependencies]
pydantic = [
    "pydantic>=2.0.0; python_version >= '3.8'"
]
# 'all' combineert nu de bovenstaande twee groepen
all = [
    "check_truststore[pydantic]",
]

[project.scripts]
check_truststore = "check_truststore.cli:main"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
check_truststore = ["locale/**/*.mo", "locale/**/*.po"]
